### PR TITLE
Fixes non-200 status code error handling

### PR DESCRIPTION
**Pull request by joelabair**
The request package does not provide an err object when an http 404 is encountered.  This commit provides error handling to the encodeFromURL method supporting 404's and non 200 responses.  Also added a default timeout and options.timeout support.

### CODE REVIEW

**Comment by DiegoZoracKy** [comment]
👍I'll try to take a look at it tomorrow. Thanks!

**Comment by DiegoZoracKy** [comment]
Hi @joelabair, thanks for pushing the PR and sorry for the delay. 

I believe that we shouldn't be firing an error for every status other than 200. The request package is just following an expected behavior.  Axios does the same, and it can be seen even in the native `fetch` method. For you to see, open the Developer Tools while on this page and execute the following:

```javascript
fetch('https://github.com/something/random/404/')
    .then(res => console.error('ok', res.status))
    .catch(err => console.error('err', err));
```

The path **/something/random/404/** doesn't exists, and even with a status 404, the response won't be handled as an error. 

Tell me what you think.

**Comment by joelabair** [comment]
Hey Diego.

In my case, I need to react to an error (non 200 status code), and its difficult to think of a use case where you wouldn't. In a Nodejs HTTP server (i.e. Express) not throwing exceptions on error causes the request to simply stall and timeout.  If a non 200 doesn't throw, I have nothing to react to.  

In the remainder of the library, a reject is called when, for example, the readFile callback is called with an error first.  This simply follows that pattern, if a HTTP request returns a non-200 status reject w/ the error.

**Comment by DiegoZoracKy** [comment]
You are totally right. Can you change the version on package.json to 2.0.0? We will be breaking a contract here, so we should bump the major version.

**Comment by joelabair** [comment]
See this thread related to the Fetch API designed behavior.  https://github.com/github/fetch/issues/155 
This is exactly the use case mislav describes.  The request API returns a success to the caller - in your code you were processing a 200, and simply not reacting to anything else.  

- Yep I'm happy to bump the version.

**Comment by joelabair** [comment]
All set.  let me know when a new release is up.

**Comment by DiegoZoracKy** [comment]
Done! 
Version 2.0.0 released on npm and here on GitHub.

Thanks @joelabair.

**Comment by joelabair** [comment]
Awesome!

**Pull request merged**
